### ISSUE TITLE
[BUG] Is "NVIDIA GeForce RTX 5060 Laptop GPU 12.0 " supported?

### ISSUE THREAD

**Issue by GingerMoon** [lightly-ai/lightly-train#347]
### 🧠 Describe the Bug

I got an error:
RuntimeError: CUDA error: no kernel image is available for execution on the device

Is my hardware supported?

My env info:

```
[2025-10-13 18:27:05,692][DEBUG] Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
[2025-10-13 18:27:05,692][DEBUG] Python: 3.12.11
[2025-10-13 18:27:05,692][DEBUG] LightlyTrain: 0.11.4
[2025-10-13 18:27:05,692][DEBUG] LightlyTrain Git Information:
[2025-10-13 18:27:05,692][DEBUG]  LightlyTrain is not installed from a git repository.
[2025-10-13 18:27:05,692][DEBUG] Run directory Git Information:
[2025-10-13 18:27:05,692][DEBUG]  The code is not running from a git repository.
[2025-10-13 18:27:05,692][DEBUG] Dependencies:
[2025-10-13 18:27:05,692][DEBUG]  - torch                       2.5.1
[2025-10-13 18:27:05,692][DEBUG]  - torchvision                0.20.1
[2025-10-13 18:27:05,692][DEBUG]  - pytorch-lightning           2.5.5
[2025-10-13 18:27:05,692][DEBUG]  - Pillow                     11.3.0
[2025-10-13 18:27:05,692][DEBUG]  - pillow-simd                     x
[2025-10-13 18:27:05,692][DEBUG] Optional dependencies:
[2025-10-13 18:27:05,692][DEBUG]  - super-gradients                 x
[2025-10-13 18:27:05,692][DEBUG]  - timm                            x
[2025-10-13 18:27:05,692][DEBUG]  - ultralytics                     x
[2025-10-13 18:27:05,692][DEBUG]  - wandb                           x
[2025-10-13 18:27:05,692][DEBUG] CPUs: 24
[2025-10-13 18:27:05,692][DEBUG] GPUs: 1
[2025-10-13 18:27:05,692][DEBUG]  - NVIDIA GeForce RTX 5060 Laptop GPU 12.0 (8546484224)
```

**Comment by stegmuel** [comment]
Hi,

This is caused by `torch==2.5.1` in our dependencies, which is itself there for compatibility with `pytorch-lightning`. 
In practice, using more recent torch version works well. For instance, using torch 2.7 worked without issues on B200 GPUs. After installing `lightly-train` you can do the following:
`pip install torch==2.7.0 torchvision==0.22.0 --index-url https://download.pytorch.org/whl/cu128` (update based on you CUDA version)

Let me know if that does not fix your issue.

**Comment by yutong-xiang-97** [comment]
Hi @GingerMoon,

I am not an expert of NVIDIA GPU on Windows, but if you can confirm the compute compatibility of your GPU to be `sm_120` (as stated [here](https://developer.nvidia.com/cuda-gpus)), then unfortunately you may need the nightly version of PyTorch, or build from source on your own, since it seems that `sm_120` is not officially supported by any stable version of PyTorch up to now. You can have a look [here](https://discuss.pytorch.org/t/pytorch-support-for-sm120/216099/66?page=2) for more details of how to handle this.

Also I am slightly confused why you have such a low CUDA version. With the nightly/latest PyTorch version you shall use at least `cu126`. `cu120` is nowhere directly supported by PyTorch. Even though it should work because of the minor version compatibility, there is still possibility for issues or limitations.

In any case, you can check if Thomas' suggestion work for you or even using PyTorch 2.8.0. We will increase the limit of PyTorch vers. of LightlyTrain shortly.

**Comment by GingerMoon** [comment]
> Hi,
> 
> This is caused by `torch==2.5.1` in our dependencies, which is itself there for compatibility with `pytorch-lightning`. In practice, using more recent torch version works well. For instance, using torch 2.7 worked without issues on B200 GPUs. After installing `lightly-train` you can do the following: `pip install torch==2.7.0 torchvision==0.22.0 --index-url https://download.pytorch.org/whl/cu128` (update based on you CUDA version)
> 
> Let me know if that does not fix your issue.

Hi @stegmuel  @yutong-xiang-97 ,

The command "pip install lightly-train" will uninstall my intalled pytorch (12.9). 
So after that I reinstall pytorch 12.9, and it works.

Thank you both for your solutions and It works!
